package org.vovochka.fun.secret.automation;

public enum BotState {
    IDLE,
    SWITCHING_ACCOUNT,
    WAITING_VPN_CHANGE,
    CONNECTING_TO_SERVER,
    WAITING_CAPTCHA,
    WAITING_CAPTCHA_ANSWER,
    HANDLING_AUTH,
    JOINING_QUEUE,
    WAITING_SPAWN,
    WRITING_FREE,
    HANDLING_FREE_MENU_1,
    HANDLING_FREE_MENU_2,
    WALKING_TO_CASE_1,
    OPENING_CASE_1,
    WALKING_TO_CASE_2,
    OPENING_CASE_2,
    PAYING_BANK,
    CREATING_STAVKA,
    ACCEPTING_STAVKA,
    WAITING_STAVKA_RESULT,
    CYCLE_COMPLETE,
    ERROR,
    BANNED
}